import { UserTableHeader } from './user-table-header';

export class UserTableData {
  tblHeader: UserTableHeader[] = [
    {
      columnName: 'checkBox',
      displayName: 'Select Item',
      class: '',
      dropDown: false,
      icon: false,
      visible: false,
      span: false,
      link: false,
      button: false,
      text: false,
      checkBox: true,
    },
    {
      columnName: 'name',
      displayName: 'Name',
      class: '',
      dropDown: false,
      icon: false,
      visible: true,
      span: true,
      link: false,
      button: false,
      text: false,
    },
    {
      columnName: 'email',
      displayName: 'Email Address',
      class: '',
      dropDown: false,
      icon: false,
      visible: true,
      span: true,
      link: false,
      button: false,
      text: false,
    },
    {
      columnName: 'role',
      displayName: 'Role',
      class: '',
      dropDown: false,
      icon: false,
      visible: true,
      span: true,
      link: false,
      button: false,
      text: false,
    },
    {
      columnName: 'subTier',
      displayName: 'Sub. Tier',
      class: '',
      dropDown: false,
      icon: false,
      visible: true,
      span: true,
      link: false,
      button: false,
      text: false,
    },
    {
      columnName: 'assignedJobs',
      displayName: 'Assigned Jobs / Access Type',
      class: '',
      dropDown: false,
      icon: false,
      visible: true,
      span: false,
      link: true,
      button: false,
      text: false,
    },
    {
      columnName: 'action',
      displayName: 'Action',
      class: '',
      dropDown: false,
      icon: true,
      visible: false,
      span: false,
      link: false,
      button: true,
      text: false,
    },
    {
      columnName: 'permission',
      displayName: 'Permission',
      class: '',
      dropDown: false,
      icon: false,
      visible: true,
      span: false,
      link: true,
      button: false,
      text: false,
    },
  ];

  actionButton = [
    {
      icon: 'fa-pencil',
      tooltip: 'Edit User Information',
      dataBsToggle: 'modal',
      dataBsTarget: '#information',
    },
    {
      icon: 'fa-info-circle',
      tooltip: 'Login History',
      dataBsToggle: 'modal',
      dataBsTarget: '#login',
    },
    {
      icon: 'fa-envelope',
      tooltip: 'Email Security Reset Information',
      dataBsToggle: 'modal',
      dataBsTarget: '#emailSecurity',
    },
    {
      icon: 'fa-lock',
      tooltip: 'Reset Password to Default',
      dataBsToggle: 'modal',
      dataBsTarget: '#password',
    },
  ];

  linkButton = [
    {
      permission: 'Edit',
      dataBsToggle: 'modal',
      dataBsTarget: '#permissionsEdit',
    },
  ];

  tblData = [
    {
      id: 1,
      checkBox: false,
      name: 'York Leng',
      email: 'yorkleng.k@gmail.com',
      role: 'Admin',
      subTier: 'Enterprise',
      assignedJobs: 'View/Edit',
      action: this.actionButton,
      permission: this.linkButton,
    },
    {
      id: 2,
      checkBox: false,
      name: 'Billy Jackson',
      email: 'billy.j@abcgroup.com',
      role: 'Project Manager',
      subTier: 'Basic',
      assignedJobs: 'View/Edit',
      action: this.actionButton,
      permission: this.linkButton,
    },
    {
      id: 3,
      checkBox: false,
      name: 'Cathy Seger',
      email: 'carlos.s@gmail.com',
      role: 'Client',
      subTier: 'Free',
      assignedJobs: 'View/Edit',
      action: this.actionButton,
      permission: this.linkButton,
    },
  ];
}
